# Generated by Django 5.2.8 on 2025-12-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_election_candidate_position_voter_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='election',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='election',
            name='title',
        ),
        migrations.AddField(
            model_name='election',
            name='name',
            field=models.CharField(choices=[('national', 'National Elections')], default='National Elections', max_length=100),
            preserve_default=False,
        ),
    ]
