# Generated by Django 5.2.8 on 2025-12-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_remove_election_end_date_remove_election_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='date_voted',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='election',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.election'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/images/'),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(choices=[('national', 'National Elections')], max_length=200),
        ),
    ]
