# Generated by Django 5.2.8 on 2025-12-10 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_rename_date_voted_vote_timestamp_election_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='election',
            name='title',
            field=models.CharField(default='General Election', max_length=200),
        ),
        migrations.AddField(
            model_name='leader',
            name='position',
            field=models.CharField(default='President', max_length=1000),
        ),
        migrations.AddField(
            model_name='leader',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(choices=[('national', 'National Elections'), ('local', 'Local Elections')], max_length=200),
        ),
        migrations.AlterField(
            model_name='leader',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
